const CardsActionTypes = {
  REVEAL_CARD: 'REVEAL_CARD',
  CREATE_DECK: 'CREATE_DECK',
  RESET_DECK: 'RESET_DECK',
  HIDE_ALL: 'HIDE_ALL',
  ADD_CARD_ACTIVE: 'ADD_CARD_ACTIVE',
  RESET_CARDS_ACTIVE: 'RESET_CARDS_ACTIVE',
  SET_CARDS_TO_MATCHED: 'SET_CARDS_TO_MATCHED',
};

export default CardsActionTypes;
